notifications:
  recipients:
    - main@sharetribe.flowdock.com

# select branches to build
branches:
  only:
    - master
    - develop

before_script:
  - mysql -e 'create database sharetribe_test;'
  - "cp config/database.example.yml config/database.yml"
  - "bundle exec rake db:schema:load"