# config/rackspace.yml
development:
  container: rgf_development
  username: foodswap
  api_key: 29aa023c1c0e7369cfb15ec09623d288

production:
  #assigned development bucket for now
  container: rgf_development
  username: foodswap
  api_key: 29aa023c1c0e7369cfb15ec09623d288

test:
  container: test_development
  username: foodswap
  api_key: 29aa023c1c0e7369cfb15ec09623d288


  
