require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SwapItemsController do

  # This should return the minimal set of attributes required to create a valid
  # SwapItem. As you add validations to SwapItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SwapItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all swap_items as @swap_items" do
      swap_item = SwapItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:swap_items).should eq([swap_item])
    end
  end

  describe "GET show" do
    it "assigns the requested swap_item as @swap_item" do
      swap_item = SwapItem.create! valid_attributes
      get :show, {:id => swap_item.to_param}, valid_session
      assigns(:swap_item).should eq(swap_item)
    end
  end

  describe "GET new" do
    it "assigns a new swap_item as @swap_item" do
      get :new, {}, valid_session
      assigns(:swap_item).should be_a_new(SwapItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested swap_item as @swap_item" do
      swap_item = SwapItem.create! valid_attributes
      get :edit, {:id => swap_item.to_param}, valid_session
      assigns(:swap_item).should eq(swap_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SwapItem" do
        expect {
          post :create, {:swap_item => valid_attributes}, valid_session
        }.to change(SwapItem, :count).by(1)
      end

      it "assigns a newly created swap_item as @swap_item" do
        post :create, {:swap_item => valid_attributes}, valid_session
        assigns(:swap_item).should be_a(SwapItem)
        assigns(:swap_item).should be_persisted
      end

      it "redirects to the created swap_item" do
        post :create, {:swap_item => valid_attributes}, valid_session
        response.should redirect_to(SwapItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved swap_item as @swap_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        SwapItem.any_instance.stub(:save).and_return(false)
        post :create, {:swap_item => {}}, valid_session
        assigns(:swap_item).should be_a_new(SwapItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SwapItem.any_instance.stub(:save).and_return(false)
        post :create, {:swap_item => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested swap_item" do
        swap_item = SwapItem.create! valid_attributes
        # Assuming there are no other swap_items in the database, this
        # specifies that the SwapItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SwapItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => swap_item.to_param, :swap_item => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested swap_item as @swap_item" do
        swap_item = SwapItem.create! valid_attributes
        put :update, {:id => swap_item.to_param, :swap_item => valid_attributes}, valid_session
        assigns(:swap_item).should eq(swap_item)
      end

      it "redirects to the swap_item" do
        swap_item = SwapItem.create! valid_attributes
        put :update, {:id => swap_item.to_param, :swap_item => valid_attributes}, valid_session
        response.should redirect_to(swap_item)
      end
    end

    describe "with invalid params" do
      it "assigns the swap_item as @swap_item" do
        swap_item = SwapItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SwapItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => swap_item.to_param, :swap_item => {}}, valid_session
        assigns(:swap_item).should eq(swap_item)
      end

      it "re-renders the 'edit' template" do
        swap_item = SwapItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SwapItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => swap_item.to_param, :swap_item => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested swap_item" do
      swap_item = SwapItem.create! valid_attributes
      expect {
        delete :destroy, {:id => swap_item.to_param}, valid_session
      }.to change(SwapItem, :count).by(-1)
    end

    it "redirects to the swap_items list" do
      swap_item = SwapItem.create! valid_attributes
      delete :destroy, {:id => swap_item.to_param}, valid_session
      response.should redirect_to(swap_items_url)
    end
  end

end
